name : Hola Mundo

on: 
  workflow_dispatch: # ejecución manual
  #push:
      #branches :
              #- main
      #paths:
           #- 'BibliotecaAPI/**'
           #- '.github/workflows/hola-mundo.yml'
  #pull_request:
     # branches:
          #- main
jobs:
 saludar:
    runs-on: ubuntu-latest
    steps: 
      - name : Muestra mensaje Hola Mundo
        run: echo "Hola Mundo Aaron"

      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name : Listar los archivos del repositorio
        run : | 
          echo "El repositorio ${{ github.repository }} contiene los siguietes archivos:"
          tree
